# Solving Systems of Linear Equations with NumPy - Lab

## Introduction 

Now you've gathered all the required skills needed to solve systems of linear equations. You saw why there was a need to calculate inverses of matrices, followed by matrix multiplication to figure out the values of unknown variables. 

The exercises in this lab present some problems that can be converted into a system of linear equations. 

## Objectives
You will be able to:

- Use matrix algebra and NumPy to solve a system of linear equations given a real-life example 
- Use NumPy's linear algebra solver to solve for systems of linear equations

## Exercise 1

A coffee shop is having a sale on coffee and tea. 

On day 1, 29 bags of coffee and 41 bags of tea were sold, for a total of 490 dollars.

On day 2, they sold 23 bags of coffee and 41 bags of tea, for which customers paid a total of 448 dollars.  

How much does each bag cost?

In [1]:
import numpy as np

In [3]:
# Create and solve the relevant system of equations
# 29c + 41t = 490
# 23c + 41t = 448

A = np.matrix([[29,41],[23,41]])
B = np.matrix([490,448])

A_inv = np.linalg.inv(A)
B = B.T

X = A_inv.dot(B)

print(X)


[[7.]
 [7.]]


In [4]:
# Describe your result
# First we construct a matrix A, with the coefficients' scalars, and a matrix B, with the equations scalars (results). 
# X should equalt the dot product of the inverse of A and B
# So first we get the inverse of A, the transpose be to make it compatible for the dot product operation
# the dot product operation result tells us that each bag cost 7 dollars. 

## Exercise 2

The cost of admission to a popular music concert was 162 dollars for 12 children and 3 adults. 

The admission was 122 dollars for 8 children and 3 adults in the same music concert. 

How much was the admission for each child and adult?

In [6]:
# Create and solve the relevant system of equations
# 12c + 3a = 162
# 8c + 3a = 122

A = np.matrix([[12,3],[8,3]])
B = np.matrix([162,122])

X = np.linalg.solve(A,B.T)
print(X)


[[10.]
 [14.]]


In [7]:
# Describe your result
# I chose to code the above in a much less verbose way from the previous problem,
# but the underlying math and therefore the result is all the same. 

# because the first column in A represents children, and the second adults
# likewise for X; children's admission cost $10 and adults $14


## Exercise 3

You want to make a soup containing tomatoes, carrots, and onions.

Suppose you don't know the exact mix to put in, but you know there are 7 individual pieces of vegetables, and there are twice as many tomatoes as onions, and that the 7 pieces of vegetables cost 5.25 USD in total. 
You also know that onions cost 0.5 USD each, tomatoes cost 0.75 USD and carrots cost 1.25 USD each.

Create a system of equations to find out exactly how many of each of the vegetables are in your soup.

In [8]:
# Create and solve the relevant system of equations
#                 o + t + c = 7 
# t  = 2o ---> -2o + t + 0c = 0 
#      0.5o + 0.75t + 1.35c = 5.25


A = np.matrix([[1,1,1],[-2,1,0],[0.5,.75,1.35]])
B = np.matrix([7,0,5.25])

X = np.linalg.solve(A,B.T)
print(X)


[[2.04878049]
 [4.09756098]
 [0.85365854]]


In [9]:
# Describe your result
# onions are $2.05 each, tomatoes are $4.10 each, and carrots are $0.85 each

## Exercise 4

A landlord owns 3 properties: a 1-bedroom(a), a 2-bedroom(b), and a 3-bedroom(c) house. 

The total rent he receives is 1240 USD. 

He needs to make some repairs, where those repairs cost 10% of the 1-bedroom house’s rent. The 2-bedroom repairs cost 20% of the 2-bedroom rental price and 30% of the 3-bedroom house's rent for its repairs.  The total repair bill for all three houses was 276 USD. 

The 3-bedroom house's rent is twice the 1-bedroom house’s rent. 

How much is the individual rent for three houses?

In [10]:
# Create and solve the relevant system of equations
#                a + b + c = 1240
#        .10a +.20b + .30c = 276
# c = 2a ---> -2a + 0b + c = 0

A = np.matrix([[1,1,1],[.1,.2,.3],[-2,0,1]])
B = np.matrix([1240,276,0])

X = np.linalg.solve(A,B.T)

print(X)

[[280.]
 [400.]
 [560.]]


In [11]:
# Describe your result
# The rent for a 1-bedroom is $280, 2-bedroom is $400 and the 3-bedroom is $560

## Summary
In this lab, you learned how to use NumPy to solve linear equations by taking inverses and matrix multiplication and also using numpy's `solve()` function. You'll now take these skills forward and see how you can define a simple regression problem using linear algebra and solve it with Numpy. 